version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn djangoProject.wsgi --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres:16-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env.db
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
        ports:
            - "1337:80"
        depends_on:
            - web
    nextjs:
        build:
            context: ../liaksej-tiny-cloud-frontend
            dockerfile: Dockerfile
        expose:
            - 3000
        env_file:
            - ../liaksej-tiny-cloud-frontend/.env.production
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
    media_volume: