# Generated by Django 4.2.7 on 2023-11-28 20:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("full_name", models.JSONField(max_length=200)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("admin", models.BooleanField()),
                ("pass_to_store", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("original_name", models.CharField(max_length=100)),
                ("file_path", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_downloaded", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("size", models.IntegerField()),
                ("file_type", models.CharField(max_length=50)),
                ("public_url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cloud.user"
                    ),
                ),
            ],
        ),
    ]
