# Generated by Django 4.2.7 on 2023-12-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0002_remove_user_admin_remove_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="cloud.user",
            ),
        ),
    ]
