# Generated by Django 4.2.7 on 2023-12-01 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cloud", "0003_alter_file_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="clouduser",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
