# Generated by Django 4.2.7 on 2023-12-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0004_alter_user_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pass_to_store",
        ),
        migrations.AddField(
            model_name="user",
            name="path_to_store",
            field=models.URLField(default="http://lalala.ru"),
            preserve_default=False,
        ),
    ]
