# Generated by Django 5.0 on 2023-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0006_alter_file_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="public_url",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
