# Generated by Django 5.0 on 2023-12-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0007_alter_file_public_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="date_downloaded",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
