# Generated by Django 5.0 on 2023-12-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0008_alter_file_date_downloaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(max_length=150),
        ),
    ]
